services:
  postgres:
    image: debezium/postgres:14-alpine
    restart: unless-stopped
    container_name: postgres-quiz
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d quiz" ]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: { }
