spring:
  application:
    name: Quiz
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: root
    password: root

security-configurations:
  jwt:
    secret: ${JWT_SECRET:/g0lkq/qOxZ3tXv4CVOkYSJVoRc3WVpTHDRTgM8QDaKS/5kihyUg2JaBrDyODHal}
    expiration: 720000

access:
  code:
    length: 7