CREATE SEQUENCE quiz_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE QUIZ(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    IS_DONE BOOLEAN NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID)
);