CREATE SEQUENCE question_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE QUESTION (
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    QUIZ_ID BIGINT NOT NULL REFERENCES QUIZ(ID)
);